dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - env CFLAGS=--coverage coverage run --source=detools setup.py test
  - make test-c

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy

deploy:
  provider: pypi
  username: __token__
  password:
    secure: ZwM31HtpIPQaxiYzC536yl50CbG67kb/4mBaHKQl3zDzfuf0ozy28FNVKxA14jZvbKD0FUChQ8/xlvW8qZteYsxfYKT3LZbWLmaOFv4SftLv9pORvzx5Zewr4pUsd4HqC7AkMUu0KC1ZKFe/maM5AWH41i/XLxHAOAqBMRe7T+4npnAeXRYDaVISQmJkYgwbqenDS9xPi6buJLokjp0tomxTUnId2yiDSi4+FEDkG5A3/Qwn+HQZW8TvqxbMi4xu2YbsPUzsrOTtxvLP3kKiqGP88kC/eknvxdn8B6fV1utqBlbgu9/vOxSRDFzuUe1T76lThNQ2icRHzXs6iBBN4iS2N/lEMQqnv4daTJk1ExUlvS3jRzpNxMd45J2svChY05s47r9mdpo7llTisb5EkUIPdW0fqqwxsXSTGeCb1+cb+RXBm3JKOqizt/aOh77sJHS/RfVEOR0JFiKoedFfMRUzDO2zlCD99Fi1flqqHt+ICwofAZzMqccX0rrwrTIpslgFXRPCSYO6LOBwYHeP61zcsBMSNU2xXPqGLaNQe9aZz2sQkS3zfCjJI/iqgzxe6Y4n2WVLd50JzUtMQIHGADw3vs+qO1I/w3seGb6IcoP2ZhLUK7xDMCMZMpyv/de0r6krAAdlluPGUQFS9LkBWZvdlhHl7YRuYWvgdlOfGU0=
  edge: true
  skip_existing: true
  on:
    tags: true
