dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install coveralls

script:
  - env CFLAGS=--coverage coverage run --source=detools setup.py test
  - make test-sdist
  - make test-c
  - env PYTHON=python tests/benchmark.sh

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
